Fix Ajv type in `onCreateAjv`
When trying to compile our project with TypeScript 4.5.5 we are receiving a build error in your lib.

```
node_modules/objection/typings/objection/index.d.ts:1213:22 - error TS2709: Cannot use namespace 'Ajv' as a type.

1213     onCreateAjv(ajv: Ajv): void;
```

The proposed change references the `Ajv` interface in the `Ajv` namespace, which is probably what you mean to do here?